" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype on

" Enable plugins and load plugin for the detected file type.
filetype plugin on

" Load an indent file for the detected file type.
filetype indent on

" Turn syntax highlighting on.
syntax on

" Show current line number
set number

" Show relative line numbers
set relativenumber

" Set color theme
colorscheme mytheme


" LIGHTLINE

" Set lightline color theme
let g:lightline = {'colorscheme': 'wombat',}

" Show lightline status line
set laststatus=2

" Prevent lightline lag
set ttimeout ttimeoutlen=0 

" Hide file info at bottom
set shortmess=F

" Don't show mode at bottom
set noshowmode


" VIMPLUG

" Specify vim-plug plugins
call plug#begin('~/.vim/plugged')
Plug 'itchyny/lightline.vim'
call plug#end()